name: Lifesteal
version: '${project.version}'
author: "SNWCreations"
main: snw.lifesteal.Main
api-version: 1.16

commands:
  lifesteal:
    description: "Lifesteal 插件功能的总开关。"
    usage: "/lifesteal"
    permission: op
    permission-message: You do not have <permission>
  heart:
    description: "使用此命令取出你的心(即血量上限)，作为物品。"
    usage: "/heart <数量>"